//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarsGroup.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainEntities : DbContext
    {
        public MainEntities()
            : base("name=MainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DownloadGames> DownloadGames { get; set; }
        public virtual DbSet<GameTypes> GameTypes { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<Statistics> Statistics { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<OnLineGames> OnLineGames { get; set; }
        public virtual DbSet<UsersInOnLineGame> UsersInOnLineGame { get; set; }
        public virtual DbSet<StatusUserInGame> StatusUserInGame { get; set; }
        public virtual DbSet<StatusGame> StatusGame { get; set; }
    }
}
