//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarsGroup.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class OnLineGames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnLineGames()
        {
            this.UsersInOnLineGame = new ObservableCollection<UsersInOnLineGame>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string LocationOfCheckers { get; set; }
        public string GameLog { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<UsersInOnLineGame> UsersInOnLineGame { get; set; }
        public virtual StatusGame StatusGame { get; set; }
    }
}
