//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarsGroup.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Score
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int GameTypeID { get; set; }
        public float Score1 { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
    
        public virtual GameTypes GameTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
