//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarsGroup.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class UsersInOnLineGame
    {
        public int ID { get; set; }
        public int GameID { get; set; }
        public int UserID { get; set; }
        public int StatusID { get; set; }
    
        public virtual OnLineGames OnLineGames { get; set; }
        public virtual Users Users { get; set; }
        public virtual StatusUserInGame StatusUserInGame { get; set; }
    }
}
